import type { Asset } from '@/types/index';

export const mockAssets: Asset[] = [
  {
    id: 'asset_1',
    clientId: 'client_1',
    title: 'Summer Workout Challenge',
    description: 'Instagram reel showcasing summer fitness routines',
    type: 'reel',
    status: 'approved',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-05-15'),
    assignedTo: ['user_3'],
    revisions: [],
    comments: [
      {
        id: 'comment_1',
        assetId: 'asset_1',
        userId: 'user_2',
        type: 'comment',
        message: 'Great energy in this reel!',
        authorId: 'user_2',
        content: 'Great energy in this reel!',
        createdAt: new Date('2024-05-13'),
        updatedAt: new Date('2024-05-13'),
        replies: [],
        isInternal: false,
      },
    ],
  },
  {
    id: 'asset_2',
    clientId: 'client_1',
    title: 'New Membership Promo',
    description: 'Promotional poster for new membership packages',
    type: 'poster',
    status: 'revision_requested',
    createdAt: new Date('2024-05-12'),
    updatedAt: new Date('2024-05-17'),
    assignedTo: ['user_3'],
    revisions: [
      {
        id: 'rev_1',
        assetId: 'asset_2',
        userId: 'user_2',
        type: 'revision',
        message: 'Adjust color to match brand guidelines',
        version: 1,
        createdBy: 'user_2',
        createdAt: new Date('2024-05-14'),
        reason: 'Adjust color to match brand guidelines',
        updatedAt: new Date('2024-05-14'),
      },
    ],
    comments: [
      {
        id: 'comment_2',
        assetId: 'asset_2',
        userId: 'user_2',
        type: 'comment',
        message: 'Please adjust the CTA button color to match our primary brand',
        authorId: 'user_2',
        content: 'Please adjust the CTA button color to match our primary brand',
        createdAt: new Date('2024-05-15'),
        updatedAt: new Date('2024-05-15'),
        replies: [],
        isInternal: false,
      },
      {
        id: 'comment_3',
        assetId: 'asset_2',
        userId: 'user_3',
        type: 'internal_note',
        message: 'Will update by EOD',
        authorId: 'user_3',
        content: 'Will update by EOD',
        createdAt: new Date('2024-05-16'),
        updatedAt: new Date('2024-05-16'),
        replies: [],
        isInternal: true,
      },
    ],
  },
  {
    id: 'asset_3',
    clientId: 'client_2',
    title: 'Espresso Special Menu',
    description: 'Carousel showing new espresso drink menu',
    type: 'poster',
    status: 'ready_for_review',
    createdAt: new Date('2024-05-14'),
    updatedAt: new Date('2024-05-17'),
    assignedTo: ['user_4'],
    revisions: [],
    comments: [],
  },
  {
    id: 'asset_4',
    clientId: 'client_3',
    title: 'Product Launch Teaser',
    description: 'Story frames for new product launch countdown',
    type: 'reel',
    status: 'draft',
    createdAt: new Date('2024-05-16'),
    updatedAt: new Date('2024-05-17'),
    assignedTo: ['user_4'],
    revisions: [],
    comments: [],
  },
  {
    id: 'asset_5',
    clientId: 'client_4',
    title: 'Summer Collection Lookbook',
    description: 'Professional product photography carousel',
    type: 'poster',
    status: 'scheduled',
    createdAt: new Date('2024-05-08'),
    updatedAt: new Date('2024-05-16'),
    assignedTo: ['user_3'],
    revisions: [
      {
        id: 'rev_2',
        assetId: 'asset_5',
        userId: 'user_2',
        type: 'revision',
        message: 'Initial review complete',
        version: 1,
        createdBy: 'user_2',
        createdAt: new Date('2024-05-12'),
        reason: 'Initial review complete',
        updatedAt: new Date('2024-05-12'),
      },
    ],
    comments: [],
  },
];