import { User, Client, Asset, Notification, UploadQueue, Workspace } from '@/types/index';

export const mockUsers: User[] = [
  {
    id: 'user_1',
    email: 'sarah@agency.com',
    name: 'Sarah Chen',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user_2',
    email: 'james@agency.com',
    name: 'James Rodriguez',
    role: 'manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'user_3',
    email: 'emma@agency.com',
    name: 'Emma Thompson',
    role: 'designer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'user_4',
    email: 'alex@agency.com',
    name: 'Alex Kim',
    role: 'designer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    createdAt: new Date('2024-02-10'),
  },
];

export const mockClients: Client[] = [
  {
    id: 'client_1',
    name: 'Stellar Fitness',
    instagramHandle: '@stellarfitness',
    monthlyDeliverables: 12,
    completedDeliverables: 8,
    assignedTeamMembers: ['user_2', 'user_3'],
    brandColor: '#FF6B6B',
  },
  {
    id: 'client_2',
    name: 'Urban Cafe',
    instagramHandle: '@urbancafelife',
    monthlyDeliverables: 8,
    completedDeliverables: 6,
    assignedTeamMembers: ['user_3', 'user_4'],
    brandColor: '#4ECDC4',
  },
  {
    id: 'client_3',
    name: 'TechStart Hub',
    instagramHandle: '@techstart_hub',
    monthlyDeliverables: 16,
    completedDeliverables: 10,
    assignedTeamMembers: ['user_2', 'user_4'],
    brandColor: '#6C5CE7',
  },
  {
    id: 'client_4',
    name: 'Luxe Goods Co',
    instagramHandle: '@luxegoods',
    monthlyDeliverables: 10,
    completedDeliverables: 7,
    assignedTeamMembers: ['user_3'],
    brandColor: '#FFD93D',
  },
];

export const mockAssets: Asset[] = [
  {
    id: 'asset_1',
    clientId: 'client_1',
    title: 'Summer Workout Challenge',
    description: 'Instagram reel showcasing summer fitness routines',
    type: 'reel',
    status: 'approved',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-05-15'),
    assignedTo: ['user_3'],
    revisions: [],
    comments: [
      {
        id: 'comment_1',
        assetId: 'asset_1',
        authorId: 'user_2',
        content: 'Great energy in this reel!',
        createdAt: new Date('2024-05-13'),
        replies: [],
        isInternal: false,
      },
    ],
  },
  {
    id: 'asset_2',
    clientId: 'client_1',
    title: 'New Membership Promo',
    description: 'Promotional poster for new membership packages',
    type: 'poster',
    status: 'revision_requested',
    createdAt: new Date('2024-05-12'),
    updatedAt: new Date('2024-05-17'),
    assignedTo: ['user_3'],
    revisions: [
      {
        id: 'rev_1',
        assetId: 'asset_2',
        version: 1,
        createdBy: 'user_2',
        createdAt: new Date('2024-05-14'),
        reason: 'Adjust color to match brand guidelines',
      },
    ],
    comments: [
      {
        id: 'comment_2',
        assetId: 'asset_2',
        authorId: 'user_2',
        content: 'Please adjust the CTA button color to match our primary brand',
        createdAt: new Date('2024-05-15'),
        replies: [],
        isInternal: false,
      },
      {
        id: 'comment_3',
        assetId: 'asset_2',
        authorId: 'user_3',
        content: 'Will update by EOD',
        createdAt: new Date('2024-05-16'),
        replies: [],
        isInternal: true,
      },
    ],
  },
  {
    id: 'asset_3',
    clientId: 'client_2',
    title: 'Espresso Special Menu',
    description: 'Carousel showing new espresso drink menu',
    type: 'carousel',
    status: 'ready_for_review',
    createdAt: new Date('2024-05-14'),
    updatedAt: new Date('2024-05-17'),
    assignedTo: ['user_4'],
    revisions: [],
    comments: [],
  },
  {
    id: 'asset_4',
    clientId: 'client_3',
    title: 'Product Launch Teaser',
    description: 'Story frames for new product launch countdown',
    type: 'story',
    status: 'draft',
    createdAt: new Date('2024-05-16'),
    updatedAt: new Date('2024-05-17'),
    assignedTo: ['user_4'],
    revisions: [],
    comments: [],
  },
  {
    id: 'asset_5',
    clientId: 'client_4',
    title: 'Summer Collection Lookbook',
    description: 'Professional product photography carousel',
    type: 'carousel',
    status: 'scheduled',
    createdAt: new Date('2024-05-08'),
    updatedAt: new Date('2024-05-16'),
    assignedTo: ['user_3'],
    revisions: [
      {
        id: 'rev_2',
        assetId: 'asset_5',
        version: 1,
        createdBy: 'user_2',
        createdAt: new Date('2024-05-12'),
        reason: 'Initial review complete',
      },
    ],
    comments: [],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif_1',
    userId: 'user_1',
    type: 'approval',
    title: 'Asset Ready for Approval',
    message: 'Espresso Special Menu is ready for your review',
    relatedAssetId: 'asset_3',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'notif_2',
    userId: 'user_2',
    type: 'revision',
    title: 'Revision Requested',
    message: 'New Membership Promo needs revisions',
    relatedAssetId: 'asset_2',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'notif_3',
    userId: 'user_3',
    type: 'assigned',
    title: 'Asset Assigned to You',
    message: 'Product Launch Teaser has been assigned',
    relatedAssetId: 'asset_4',
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
];

export const mockUploadQueue: UploadQueue[] = [
  {
    id: 'queue_1',
    assetId: 'asset_1',
    scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    platform: 'instagram',
    status: 'scheduled',
    caption: 'Join our summer fitness challenge! 💪 Tag a friend who needs this.',
    hashtags: ['#fitnesschallenge', '#summer2024', '#workoutmotivation'],
  },
  {
    id: 'queue_2',
    assetId: 'asset_5',
    scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    platform: 'instagram',
    status: 'scheduled',
    caption: 'Discover our new summer collection ✨',
    hashtags: ['#summercollection', '#newlookbook', '#luxegoods'],
  },
];

export const mockWorkspace: Workspace = {
  id: 'workspace_1',
  name: 'Creative Agency Hub',
  members: [
    { id: 'tm_1', userId: 'user_1', workspaceId: 'workspace_1', role: 'admin', joinedAt: new Date('2024-01-01') },
    { id: 'tm_2', userId: 'user_2', workspaceId: 'workspace_1', role: 'manager', joinedAt: new Date('2024-01-15') },
    { id: 'tm_3', userId: 'user_3', workspaceId: 'workspace_1', role: 'designer', joinedAt: new Date('2024-02-01') },
    { id: 'tm_4', userId: 'user_4', workspaceId: 'workspace_1', role: 'designer', joinedAt: new Date('2024-02-10') },
  ],
  createdAt: new Date('2024-01-01'),
};
